# CC = g++
# CXXFLAGS += -Wall
# # CXXFLAGS += -I. -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/linux
# CXXFLAGS += -I$(JAVA_HOME)/include -std=c++14 -I$(JAVA_HOME)/include/darwin/

# .java.class:
#         $(JC) $(JFLAGS) $*.java.java.class:
#         $(JC) $(JFLAGS) $*.java

# all: libjnihelios.jnilib

# libjnihelios.jnilib: libjnihelios.o

# libjnihelios.o: 

# %.o: %.cpp
# 	$(CC) $(CXXFLAGS) 

# %.class: %.java
# 	javac $<

# %.h: %.class
# 	javah -cp . $(<:.class=)


# clean:
# 	rm -rf *.o *.class
